debounce: 300
ignore: \.git/
trig_async:
  - server
  - worker
format:
  command_ok: "\u001b[38;5;240m[{{.Title}}] \u001b[0m{{.Message}}\n"
  command_err: "\u001b[38;5;240m[{{.Title}}] \u001b[38;5;1m{{.Message}}\u001b[0m\n"
rules:
  - name: server
    match: \.go$
    ignore: (/mock/|interface\.go|/entity/|_test\.go)
    command: go run cmd/server/server.go

  - name: worker
    match: \.go$
    ignore: (/mock/|interface\.go|/entity/|_test\.go)
    command: go run cmd/worker/worker.go

  - name: gqlgen
    match: (schema\.graphql|gqlgen.yml)$
    command: gqlgen --config cmd/server/internal/graphql/gqlgen.yml

  - name: generate
    match: /interface\.go$|/entity/
    ignore: _gen\.go$
    command: go generate {PKG}
    debounce: 1000
    trig_async:
      - server
      - worker

  - name: test
    match: _test\.go$
    command: go test -cover {PKG}

  - name: lint
    match: \.go$
    ignore: (/mock/|_gen_?|((interface|entity|_test)\.go)$)
    command: golangci-lint run {PKG}
    debounce: 1000
