debounce: 300
ignore: \.git/
trig_async:
  - server
  - worker
format:
  command_ok: "\u001b[38;5;240m[{{.Title}}] \u001b[0m{{.Message}}\n"
  command_err: "\u001b[38;5;240m[{{.Title}}] \u001b[38;5;1m{{.Message}}\u001b[0m\n"
rules:
  - name: server
    match: \.go$
    ignore: ((/(iface|entity|mock)/)|_test\.go$)
    command: go run cmd/server/server.go

  - name: worker
    match: \.go$
    ignore: ((/(iface|entity|mock)/)|_test\.go$)
    command: go run cmd/worker/worker.go

  - name: gqlgen
    match: (schema\.graphql|gqlgen.yml)$
    command: gqlgen --config cmd/server/internal/graphql/gqlgen.yml

  - name: generate
    match: pkg/(iface|entity)/
    ignore: (_test\.go|_gen_?)
    command: go generate {PKG}
    debounce: 1000
    trig_async:
      - server
      - worker

  - name: test
    match: _test\.go$
    command: go test -cover {PKG}

  - name: lint
    match: \.go$
    ignore: _gen_?
    command: golangci-lint run {PKG}
    debounce: 1000
