// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: email.proto

package entity

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Email struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=Created,proto3" json:"Created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Email) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Email) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func init() {
	proto.RegisterType((*Email)(nil), "entity.Email")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x54,
	0x4a, 0xe6, 0x62, 0x75, 0x05, 0x09, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x30, 0x07, 0x31, 0x79, 0xba, 0x08, 0x89, 0x71, 0xb1, 0x85, 0x16, 0xa7, 0x16, 0x79, 0xba,
	0x48, 0x30, 0x81, 0xc5, 0xa0, 0x3c, 0x21, 0x09, 0x2e, 0x76, 0xc7, 0x94, 0x94, 0xa2, 0xd4, 0xe2,
	0x62, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x17, 0x24, 0xe3, 0x5c, 0x94, 0x9a, 0x58,
	0x92, 0x9a, 0x22, 0xc1, 0x02, 0xd6, 0x02, 0xe3, 0x26, 0xb1, 0x81, 0xed, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xea, 0x91, 0x41, 0x66, 0x82, 0x00, 0x00, 0x00,
}
