// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type AuthUserResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Email struct {
	ID      string `json:"id"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type EmailResponse struct {
	Email *Email `json:"email"`
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Emails []*Email `json:"emails"`
}

type UserResponse struct {
	User *User `json:"user"`
}

type AddEmailInput struct {
	UserID  string `json:"userID"`
	Address string `json:"address"`
}

type AddUserInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type AuthUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
