// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type Email struct {
	ID      string `json:"id"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Emails []*Email `json:"emails"`
}

type AddEmailInput struct {
	UserID  string `json:"userID"`
	Address string `json:"address"`
}

type AddUserInput struct {
	Name string `json:"name"`
}
