// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type Email struct {
	ID      int    `json:"id"`
	Address string `json:"address"`
	User    User   `json:"user"`
}

type User struct {
	ID     int      `json:"id"`
	Name   string   `json:"name"`
	Emails []*Email `json:"emails"`
}

type AddMailInput struct {
	UserID  int    `json:"userID"`
	Address string `json:"address"`
}
