name: tests
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Go
              uses: actions/setup-go@v2
              with:
                  go-version: '^1.15.2'
            - name: golangci-lint
              run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./...
            - name: Test
              run: go test -race -cover ./...
