name: tests
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Go
              uses: actions/setup-go@v2
              with:
                  go-version: '^1.15.2'
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v2
              with:
                  version: v1.31
            - name: Test
              run: make godeps && go test -race -cover ./...
